-- CreateTable
CREATE TABLE "MARA" (
    "MATNR" VARCHAR(18) NOT NULL,
    "MTART" CHAR(4) NOT NULL,
    "MATKL" VARCHAR(9),
    "MEINS" CHAR(3) NOT NULL,
    "LAEDA" DATE,

    CONSTRAINT "MARA_pkey" PRIMARY KEY ("MATNR")
);

-- CreateTable
CREATE TABLE "KNA1" (
    "KUNNR" VARCHAR(10) NOT NULL,
    "LAND1" CHAR(2),
    "ORT01" VARCHAR(25),
    "NAME1" VARCHAR(35) NOT NULL,
    "REGIO" VARCHAR(3),

    CONSTRAINT "KNA1_pkey" PRIMARY KEY ("KUNNR")
);

-- CreateTable
CREATE TABLE "VBAK" (
    "VBELN" VARCHAR(10) NOT NULL,
    "AUART" CHAR(4),
    "ERDAT" DATE,
    "KUNNR" VARCHAR(10) NOT NULL,
    "VKORG" VARCHAR(4),

    CONSTRAINT "VBAK_pkey" PRIMARY KEY ("VBELN")
);

-- CreateTable
CREATE TABLE "VBAP" (
    "VBELN" VARCHAR(10) NOT NULL,
    "POSNR" VARCHAR(6) NOT NULL,
    "MATNR" VARCHAR(18),
    "KWMENG" DECIMAL(15,3),
    "WERKS" VARCHAR(4),
    "ERDAT" DATE,

    CONSTRAINT "VBAP_pkey" PRIMARY KEY ("VBELN","POSNR")
);

-- CreateIndex
CREATE INDEX "VBAK_KUNNR_idx" ON "VBAK"("KUNNR");

-- CreateIndex
CREATE INDEX "VBAP_MATNR_idx" ON "VBAP"("MATNR");

-- CreateIndex
CREATE INDEX "VBAP_VBELN_idx" ON "VBAP"("VBELN");

-- AddForeignKey
ALTER TABLE "VBAK" ADD CONSTRAINT "VBAK_KUNNR_fkey" FOREIGN KEY ("KUNNR") REFERENCES "KNA1"("KUNNR") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VBAP" ADD CONSTRAINT "VBAP_VBELN_fkey" FOREIGN KEY ("VBELN") REFERENCES "VBAK"("VBELN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VBAP" ADD CONSTRAINT "VBAP_MATNR_fkey" FOREIGN KEY ("MATNR") REFERENCES "MARA"("MATNR") ON DELETE SET NULL ON UPDATE CASCADE;
